### ISSUE TITLE
[DDP-11] v0.2 does not run

### ISSUE THREAD

**Issue by simone-trubian** [simone-trubian/dropp-client#13]
After pushing v0.2 to the prod server the app failed to be triggered. Investigate and fix.

**Comment by simone-trubian** [comment]
The program is being triggered but is throwing an exception:
`Traceback (most recent call last):
  File "/home/ubuntu/dropp/dropp.py", line 65, in <module>
    availability_list.append(get_availability(url))
  File "/home/ubuntu/dropp/dropp.py", line 27, in get_availability
    response = get(url)
  File "/home/ubuntu/.virtualenvs/dropp27/local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ubuntu/.virtualenvs/dropp27/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/.virtualenvs/dropp27/local/lib/python2.7/site-packages/requests/sessions.py", line 451, in request
    prep = self.prepare_request(req)
  File "/home/ubuntu/.virtualenvs/dropp27/local/lib/python2.7/site-packages/requests/sessions.py", line 382, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/ubuntu/.virtualenvs/dropp27/local/lib/python2.7/site-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/home/ubuntu/.virtualenvs/dropp27/local/lib/python2.7/site-packages/requests/models.py", line 362, in prepare_url
    to_native_string(url, 'utf8')))
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?`

Likely it is caused by a wrong url in the in file. Will fetch the in file and try on my local machine.

**Comment by simone-trubian** [comment]
The problem seems to have been caused by a blank line at the end of the in file, that was parsed as empty string and processed as a normal URL. I removed the blank line, and will wait until the next cycle to close the issue.

**Comment by simone-trubian** [comment]
After removing the empty line the program started again.
